spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sensor_data
    username: postgres
    password: simo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server:
  port: 8036

openweather:
  api:
    key: e9d3f27c057febc8aa2334b703c3ce1e

weather:
  default:
    latitude: 32.3397
    longitude: -6.3608