services:
  #postgresql
  postgres:
    container_name: postgres-sql-smart-farm
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: sensor_data
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - smart-farm
    restart: unless-stopped
  #keycloak
  keycloak:
    container_name: keycloak-smart-farm
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - smart-farm
    command:
      - "start-dev"

networks:
  smart-farm:
    driver: bridge

volumes:
  postgres:
    driver: local